name: Release Obsidian plugin

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm ci

      - name: Build plugin
        run: npm run build

      - name: Check CHANGELOG.md Existence
        run: ls -l CHANGELOG.md

      - name: Debug CHANGELOG.md File Content
        run: cat CHANGELOG.md

      - name: Extract Changelog
        id: changelog
        run: |
          # Extract the latest changelog section
          changelog=$(sed -n '/^## /{h;d;};H;/^## /{x;s/^## //;p;q;}' CHANGELOG.md)
          
          # Print the raw extracted changelog
          echo "Raw Extracted Changelog: $changelog"
          
          # URL encode special characters
          changelog="${changelog//'%'/'%25'}"
          changelog="${changelog//$'\n'/'%0A'}"
          changelog="${changelog//$'\r'/'%0D'}"
          
          # Set the output
          echo "::set-output name=changelog::$changelog"

      - name: Debug Changelog Output
        run: echo ${{ steps.changelog.outputs.changelog }}

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"

          gh release create "$tag" \
            --title="$tag" \
            --notes="${{ steps.changelog.outputs.changelog }}" \
            main.js manifest.json styles.css
